
tdoublet:
   - 0.09

pdoublet:
    - 0.01
    - 0.05
    - 0.09
    - 0.15
    - 0.2
    - 0.25
    - 0.3
    - 0.4
    - 0.7
    - 0.9

bprec:
    - 10

ado: 0.05

fp:
    - 0.0244

fn:
    - 0.001

seed: 1

pval:
    - 0.000001

scg_state: "scg_config/state_map.yaml"
scg_config: "scg_config/scg_config.yaml"